import {
  X,
  ShieldCheck,
  AlertTriangle,
  Building2,
  User,
  Clock,
  FileText,
  CheckCircle2,
  Info,
  ExternalLink,
  Users
} from "lucide-react";
import { COLORS } from "../../constants/colors";
import { Btn } from "../common/Btn";
import { Badge } from "../common/Badge";

export const ModalDetailMonitoringNIK = ({ data, onClose, onOpenRiwayatTiket }) => {
  if (!data) return null;

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        background: "rgba(15, 23, 42, 0.65)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1300,
        padding: 16,
        backdropFilter: "blur(3px)",
      }}
      onClick={onClose}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        style={{
          background: "#FFFFFF",
          borderRadius: 12,
          width: "100%",
          maxWidth: 680,
          maxHeight: "92vh",
          display: "flex",
          flexDirection: "column",
          boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.35)",
          border: "1px solid #CBD5E1",
          overflow: "hidden",
        }}
      >
        {/* Header Modal */}
        <div
          style={{
            padding: "16px 20px",
            borderBottom: "1px solid #E2E8F0",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            background: "#F8FAFC",
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <div
              style={{
                width: 38,
                height: 38,
                borderRadius: 8,
                background: "#EFF6FF",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                border: "1px solid #BFDBFE",
              }}
            >
              <Users size={18} color={COLORS.blue} />
            </div>
            <div>
              <div style={{ fontSize: 15, fontWeight: 800, color: "#0F172A" }}>
                Monitoring Tindak Lanjut NIK — Divisi Kepesertaan
              </div>
              <div style={{ fontSize: 11, color: "#64748B" }}>
                Pengawasan Status NIK Sementara &amp; Progres Rekonsiliasi SIAK Dukcapil
              </div>
            </div>
          </div>
          <button
            onClick={onClose}
            style={{
              background: "transparent",
              border: "none",
              cursor: "pointer",
              padding: 6,
              borderRadius: 6,
              color: "#94A3B8",
            }}
          >
            <X size={18} />
          </button>
        </div>

        {/* Modal Body */}
        <div style={{ padding: 20, overflowY: "auto", display: "flex", flexDirection: "column", gap: 16 }}>
          {/* Status Banner */}
          <div
            style={{
              background: data.isNikSementara ? "#FFFBEB" : "#F0FDF4",
              border: `1px solid ${data.isNikSementara ? "#FDE68A" : "#BBF7D0"}`,
              borderRadius: 8,
              padding: "12px 14px",
              display: "flex",
              alignItems: "flex-start",
              gap: 10,
            }}
          >
            {data.isNikSementara ? (
              <AlertTriangle size={18} color="#D97706" style={{ flexShrink: 0, marginTop: 1 }} />
            ) : (
              <CheckCircle2 size={18} color="#059669" style={{ flexShrink: 0, marginTop: 1 }} />
            )}
            <div style={{ fontSize: 12, lineHeight: 1.5 }}>
              <div style={{ fontWeight: 800, color: data.isNikSementara ? "#92400E" : "#166534" }}>
                {data.isNikSementara
                  ? "Peserta Menggunakan NIK Sementara (Auto-Generated by System)"
                  : "NIK Telah Valid & Terpadan Sempurna di Dukcapil"}
              </div>
              <div style={{ color: data.isNikSementara ? "#B45309" : "#15803D", marginTop: 2 }}>
                {data.isNikSementara
                  ? "Sistem pajak otomatis menerbitkan NIK Sementara agar potongan PPh 21 tetap dihitung dengan tarif normal (tanpa sanksi 20%). Tindak lanjut dan sinkronisasi ke Dukcapil dilakukan sepenuhnya oleh Divisi Kepesertaan."
                  : "Data kependudukan telah sinkron 100% dan siap dilaporkan ke Coretax DJP."}
              </div>
            </div>
          </div>

          {/* Grid Identitas Peserta */}
          <div
            style={{
              background: "#F8FAFC",
              borderRadius: 8,
              padding: 14,
              border: "1px solid #E2E8F0",
              display: "grid",
              gridTemplateColumns: "1fr 1fr",
              gap: 12,
              fontSize: 12,
            }}
          >
            <div>
              <span style={{ color: "#64748B", display: "block", fontSize: 10.5, fontWeight: 600 }}>NAMA LENGKAP</span>
              <strong style={{ color: "#0F172A", fontSize: 13 }}>{data.nama}</strong>
            </div>

            <div>
              <span style={{ color: "#64748B", display: "block", fontSize: 10.5, fontWeight: 600 }}>NOPENS / NRP</span>
              <span style={{ fontFamily: "monospace", fontWeight: 700, color: COLORS.blueDark }}>
                {data.nopens} • {data.nrp}
              </span>
            </div>

            <div>
              <span style={{ color: "#64748B", display: "block", fontSize: 10.5, fontWeight: 600 }}>SATKER KEDINASAN / UNOR</span>
              <span style={{ color: "#334155", fontWeight: 600 }}>{data.satker} ({data.unor})</span>
            </div>

            <div>
              <span style={{ color: "#64748B", display: "block", fontSize: 10.5, fontWeight: 600 }}>JENIS DAPEM</span>
              <span style={{ color: "#475569" }}>{data.dapem}</span>
            </div>

            <div style={{ borderTop: "1px solid #E2E8F0", paddingTop: 8 }}>
              <span style={{ color: "#64748B", display: "block", fontSize: 10.5, fontWeight: 600 }}>NIK SAAT INI (PADA SISTEM)</span>
              <span
                style={{
                  fontFamily: "monospace",
                  fontWeight: 800,
                  color: data.isNikSementara ? "#D97706" : "#059669",
                  fontSize: 12.5,
                }}
              >
                {data.nik}
              </span>
              {data.isNikSementara && (
                <div style={{ fontSize: 10, color: "#D97706", fontWeight: 700 }}>● NIK Sementara Sistem</div>
              )}
            </div>

            <div style={{ borderTop: "1px solid #E2E8F0", paddingTop: 8 }}>
              <span style={{ color: "#64748B", display: "block", fontSize: 10.5, fontWeight: 600 }}>NIK ASLI DI ARSIP (ANOMALI)</span>
              <span style={{ fontFamily: "monospace", color: "#DC2626", fontWeight: 600 }}>
                {data.nikAsli || data.nik}
              </span>
            </div>
          </div>

          {/* Rincian Monitoring Divisi Kepesertaan */}
          <div style={{ border: "1px solid #E2E8F0", borderRadius: 8, padding: 14 }}>
            <div style={{ fontSize: 12.5, fontWeight: 800, color: "#0F172A", marginBottom: 10, display: "flex", alignItems: "center", gap: 6 }}>
              <Building2 size={15} color={COLORS.blue} />
              Status Tindak Lanjut oleh Divisi Kepesertaan
            </div>

            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, fontSize: 12 }}>
              <div>
                <span style={{ color: "#64748B", display: "block", fontSize: 10.5, fontWeight: 600 }}>STATUS PROGRES KEPESERTAAN</span>
                <Badge
                  color={
                    data.statusTindakLanjut?.includes("Selesai")
                      ? "green"
                      : data.statusTindakLanjut?.includes("Dokumen")
                      ? "teal"
                      : data.statusTindakLanjut?.includes("Dikonfirmasi")
                      ? "blue"
                      : "purple"
                  }
                >
                  {data.statusTindakLanjut}
                </Badge>
              </div>

              <div>
                <span style={{ color: "#64748B", display: "block", fontSize: 10.5, fontWeight: 600 }}>PIC / PETUGAS KEPESERTAAN</span>
                <span style={{ fontWeight: 600, color: "#1E293B" }}>{data.picKepesertaan || "Divisi Kepesertaan"}</span>
              </div>

              <div>
                <span style={{ color: "#64748B", display: "block", fontSize: 10.5, fontWeight: 600 }}>TANGGAL TERBIT NIK SEMENTARA</span>
                <span style={{ color: "#475569" }}>{data.tglTerbitNIKSementara || data.tglMasukList}</span>
              </div>

              <div>
                <span style={{ color: "#64748B", display: "block", fontSize: 10.5, fontWeight: 600 }}>NO. NOTA DINAS PERMOHONAN</span>
                <span style={{ fontFamily: "monospace", color: "#1E293B" }}>{data.noSuratPengantar}</span>
              </div>
            </div>

            <div style={{ marginTop: 12, background: "#F8FAFC", padding: 10, borderRadius: 6, border: "1px solid #F1F5F9", fontSize: 11.5 }}>
              <strong style={{ color: "#334155" }}>Diagnosa Anomali Dukcapil:</strong>
              <div style={{ color: "#64748B", marginTop: 2 }}>{data.diagnosaNIK}</div>
            </div>
          </div>

          {/* Timeline Progres Terkini */}
          <div>
            <div style={{ fontSize: 12, fontWeight: 700, color: "#0F172A", marginBottom: 8, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <span>Riwayat Aktivitas Pemadanan &amp; Koordinasi</span>
              <span style={{ fontSize: 11, color: "#64748B", fontWeight: 500 }}>
                {data.riwayatLog?.length || 0} Aktivitas Tercatat
              </span>
            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
              {data.riwayatLog?.map((log, idx) => (
                <div
                  key={idx}
                  style={{
                    background: "#FFFFFF",
                    border: "1px solid #E2E8F0",
                    borderRadius: 6,
                    padding: "8px 12px",
                    fontSize: 11.5,
                  }}
                >
                  <div style={{ display: "flex", justifyContent: "space-between", color: "#64748B", fontSize: 10.5, fontWeight: 600 }}>
                    <span>{log.tgl} • {log.petugas}</span>
                    <span style={{ color: idx === data.riwayatLog.length - 1 ? "#1D4ED8" : "#64748B" }}>
                      {idx === data.riwayatLog.length - 1 ? "● Status Terakhir" : ""}
                    </span>
                  </div>
                  <div style={{ fontWeight: 700, color: "#0F172A", marginTop: 2 }}>{log.aksi}</div>
                  <div style={{ color: "#475569", marginTop: 1 }}>{log.catatan}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div
          style={{
            padding: "12px 20px",
            borderTop: "1px solid #E2E8F0",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            background: "#F8FAFC",
          }}
        >
          <div style={{ fontSize: 11, color: "#64748B" }}>
            Divisi Keuangan memonitor daftar tindak lanjut secara real-time.
          </div>
          <Btn variant="outline" size="sm" onClick={onClose}>
            Tutup
          </Btn>
        </div>
      </div>
    </div>
  );
};
